
window.mocks =
  "\\/teams":
    [
      {
        "cloudId": "19004",
        "name": "hodags",
        "season": "2012",
        "nameWithSeason": "hodags 2012",
        "password": "pisspoor",
        "numberOfGames": 8,
        "firstGameDate": "2012-03-03 15:55",
        "lastGameDate": "2012-03-18 14:45",
        "private": true,
        "playersAreLeaguevine": false,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      },
      {
        "cloudId": "21002",
        "name": "hodags",
        "season": "2012",
        "nameWithSeason": "hodags 2012",
        "numberOfGames": 8,
        "firstGameDate": "2012-03-03 15:55",
        "lastGameDate": "2012-03-18 14:45",
        "private": false,
        "playersAreLeaguevine": false,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      },
      {
        "cloudId": "23001",
        "name": "hodags",
        "season": "2012",
        "nameWithSeason": "hodags 2012",
        "numberOfGames": 8,
        "firstGameDate": "2012-03-03 15:55",
        "lastGameDate": "2012-03-18 14:45",
        "private": false,
        "playersAreLeaguevine": false,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      },
      {
        "cloudId": "24002",
        "name": "hodags",
        "season": "2012",
        "nameWithSeason": "hodags 2012",
        "numberOfGames": 8,
        "firstGameDate": "2012-03-03 15:55",
        "lastGameDate": "2012-03-18 14:45",
        "private": false,
        "playersAreLeaguevine": false,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      },
      {
        "cloudId": "29001",
        "name": "Hodags",
        "season": "2012",
        "nameWithSeason": "Hodags 2012",
        "numberOfGames": 5,
        "firstGameDate": "2012-03-31 09:58",
        "lastGameDate": "2012-04-01 13:31",
        "private": false,
        "playersAreLeaguevine": false,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      },
      {
        "cloudId": "127001",
        "teamId": "team-1DAC406A-F765-41BC-830D-BC5721A315D4",
        "name": "Sackville Baggins",
        "season": "2012",
        "nameWithSeason": "Sackville Baggins 2012",
        "leaguevineJson": "{\"id\":20922,\"name\":\"Sackville Baggins\",\"season\":{\"id\":20117,\"name\":\"2011\",\"league\":{\"id\":20098,\"name\":\"Fake League\",\"gender\":\"open\"}}}",
        "numberOfGames": 1,
        "firstGameDate": "2012-11-05 20:11",
        "lastGameDate": "2012-11-05 20:11",
        "private": false,
        "playersAreLeaguevine": false,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      },
      {
        "cloudId": "5668600916475904",
        "teamId": "team-8AB1286B-7CCB-42DA-B49A-04702115345E",
        "name": "Madison Radicals COPY",
        "season": "2013",
        "nameWithSeason": "Madison Radicals COPY 2013",
        "leaguevineJson": "{\"id\":22619,\"name\":\"Madison Radicals\",\"season\":{\"id\":20278,\"name\":\"2013\",\"league\":{\"id\":20053,\"name\":\"AUDL\",\"gender\":\"open\"}}}",
        "numberOfGames": 18,
        "firstGameDate": "2013-04-21 16:10",
        "lastGameDate": "2013-08-04 13:14",
        "private": false,
        "playersAreLeaguevine": true,
        "mixed": false,
        "displayPlayerNumber": false,
        "deleted": false
      }
    ]
  "\\/admin\\/team\\/[^\\/]*\\/games":
    [
      {
        "teamId": "19004",
        "gameId": "game-3B4A2F06-4C48-4ED9-BD7B-A4CE4D9720C4",
        "opponentName": "cal",
        "tournamentName": "centex",
        "gamePoint": 0,
        "timestamp": "2012-03-17 16:00",
        "date": "Sat, 3/17",
        "time": "4:00",
        "msSinceEpoch": 1332000000000,
        "ours": 10,
        "theirs": 8,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-89515CD9-2FC7-4634-B47F-E1EB4CBFF0E7",
        "opponentName": "Harvard",
        "tournamentName": "Stanford invite",
        "gamePoint": 0,
        "timestamp": "2012-03-03 15:55",
        "date": "Sat, 3/03",
        "time": "3:55",
        "msSinceEpoch": 1330790100000,
        "ours": 13,
        "theirs": 7,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-9B46B87C-A150-4641-9DD6-B7C77F6E3A6A",
        "opponentName": "tufts",
        "tournamentName": "centex",
        "gamePoint": 0,
        "timestamp": "2012-03-18 14:45",
        "date": "Sun, 3/18",
        "time": "2:45",
        "msSinceEpoch": 1332081900000,
        "ours": 11,
        "theirs": 6,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-F7CFCDCB-772C-4834-9441-D50D8BD6B7FA",
        "opponentName": "Texas",
        "tournamentName": "center",
        "gamePoint": 0,
        "timestamp": "2012-03-17 10:42",
        "date": "Sat, 3/17",
        "time": "10:42",
        "msSinceEpoch": 1331980920000,
        "ours": 12,
        "theirs": 11,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-C98936CE-9213-4776-8408-63C5BD501C93",
        "opponentName": "Colorado",
        "tournamentName": "centex",
        "gamePoint": 0,
        "timestamp": "2012-03-18 10:54",
        "date": "Sun, 3/18",
        "time": "10:54",
        "msSinceEpoch": 1332068040000,
        "ours": 12,
        "theirs": 9,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-67473DBA-452F-4003-8877-7EBD2AB18616",
        "opponentName": "mizzou",
        "tournamentName": "centex",
        "gamePoint": 0,
        "timestamp": "2012-03-17 09:00",
        "date": "Sat, 3/17",
        "time": "9:00",
        "msSinceEpoch": 1331974800000,
        "ours": 13,
        "theirs": 2,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-56283B7C-E2E3-43B0-A4E2-7BC12895781B",
        "opponentName": "minnesota",
        "tournamentName": "centex",
        "gamePoint": 0,
        "timestamp": "2012-03-18 12:44",
        "date": "Sun, 3/18",
        "time": "12:44",
        "msSinceEpoch": 1332074640000,
        "ours": 11,
        "theirs": 12,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      },
      {
        "teamId": "19004",
        "gameId": "game-D4B7F535-60B8-4074-9EE3-0AB6582CFEFF",
        "opponentName": "Harvard",
        "tournamentName": "centex",
        "gamePoint": 0,
        "timestamp": "2012-03-17 14:18",
        "date": "Sat, 3/17",
        "time": "2:18",
        "msSinceEpoch": 1331993880000,
        "ours": 13,
        "theirs": 4,
        "lastUpdateUtc": "2014-07-05 09:02",
        "previousVersionAvailable": false,
        "deleted": false,
        "firstPointOline": false
      }
    ]
  "\\/team\\/[^\\/]*\\/game\\/[^\\/]":
    {
      "teamId": "19004",
      "gameId": "game-3B4A2F06-4C48-4ED9-BD7B-A4CE4D9720C4",
      "opponentName": "cal",
      "tournamentName": "centex",
      "gamePoint": 0,
      "pointsJson": "[{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"brian\",\"dayu\",\"jake\",\"kelsen\",\"sam love\",\"simmons\",\"wiseman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":0,\"theirs\":1},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Drop\",\"passer\":\"dan park\",\"receiver\":\"jordan\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"becker\",\"colin\",\"dan park\",\"jordan\",\"simmons\",\"aaron\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":0,\"theirs\":2},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"colin\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"colin\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"dan park\",\"receiver\":\"brian\",\"timestamp\":0.0}],\"line\":[\"brian\",\"colin\",\"dan park\",\"jordan\",\"pat\",\"simmons\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":1,\"theirs\":2},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"alter\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"kelsen\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"danny\",\"receiver\":\"zeman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"zeman\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"alter\",\"receiver\":\"coolidge\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"coolidge\",\"receiver\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Drop\",\"passer\":\"danny\",\"receiver\":\"kelsen\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"tuna\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"kelsen\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"kelsen\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"alter\",\"receiver\":\"zeman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"zeman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"kelsen\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"kelsen\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"alter\",\"receiver\":\"tuna\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"tuna\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"rainy\",\"receiver\":\"coolidge\",\"timestamp\":0.0}],\"line\":[\"alter\",\"coolidge\",\"danny\",\"kelsen\",\"tuna\",\"zeman\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":2,\"theirs\":2},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"dayu\",\"jake\",\"sam love\",\"shane\",\"simmons\",\"turtle\",\"wiseman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":2,\"theirs\":3},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"pat\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"pat\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"aaron\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"aaron\",\"receiver\":\"pat\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"pat\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"simmons\",\"receiver\":\"rainy\",\"timestamp\":0.0}],\"line\":[\"becker\",\"brian\",\"dan park\",\"pat\",\"simmons\",\"aaron\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":3,\"theirs\":3},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"coolidge\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"jake\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"jake\",\"receiver\":\"coolidge\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"coolidge\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"wiseman\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"wiseman\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"dayu\",\"receiver\":\"wiseman\",\"timestamp\":0.0}],\"line\":[\"alter\",\"coolidge\",\"dayu\",\"jake\",\"simmons\",\"tuna\",\"wiseman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":4,\"theirs\":3},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"craig\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"craig\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"colin\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"colin\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"danny\",\"receiver\":\"craig\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"craig\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Drop\",\"passer\":\"alter\",\"receiver\":\"colin\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"craig\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"craig\",\"receiver\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"wiseman\",\"receiver\":\"colin\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"colin\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"alter\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"danny\",\"receiver\":\"peter\",\"timestamp\":0.0}],\"line\":[\"alter\",\"craig\",\"danny\",\"kelsen\",\"peter\",\"wiseman\",\"zeman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":5,\"theirs\":3},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"jake\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"turtle\",\"receiver\":\"sam love\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"sam love\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"turtle\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"turtle\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"coolidge\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"coolidge\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"turtle\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"turtle\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"jake\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"jake\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"coolidge\",\"dayu\",\"jake\",\"sam love\",\"shane\",\"turtle\",\"zeman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":5,\"theirs\":4},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"colin\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"colin\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Drop\",\"passer\":\"simmons\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"colin\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"colin\",\"receiver\":\"jordan\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"jordan\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"becker\",\"colin\",\"dan park\",\"jordan\",\"simmons\",\"aaron\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":5,\"theirs\":5},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"brian\",\"colin\",\"dan park\",\"jordan\",\"pat\",\"simmons\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":5,\"theirs\":6},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"becker\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"becker\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"becker\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"becker\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"becker\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"becker\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"brian\",\"receiver\":\"becker\",\"timestamp\":0.0}],\"line\":[\"becker\",\"colin\",\"dan park\",\"jordan\",\"simmons\",\"aaron\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":6,\"theirs\":6},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"alter\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"kelsen\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"kelsen\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"kelsen\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"kelsen\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"kelsen\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"coolidge\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"coolidge\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"alter\",\"receiver\":\"jake\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"jake\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dayu\",\"receiver\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"wiseman\",\"receiver\":\"coolidge\",\"timestamp\":0.0}],\"line\":[\"alter\",\"coolidge\",\"dayu\",\"jake\",\"kelsen\",\"simmons\",\"wiseman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":7,\"theirs\":6},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"pat\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"pat\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"becker\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"becker\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Drop\",\"passer\":\"rainy\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"aaron\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"aaron\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"aaron\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"aaron\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"rainy\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"rainy\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"rainy\",\"receiver\":\"becker\",\"timestamp\":0.0}],\"line\":[\"becker\",\"brian\",\"dan park\",\"pat\",\"simmons\",\"aaron\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":8,\"theirs\":6},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"kelsen\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"danny\",\"receiver\":\"jake\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"jake\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"wiseman\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"danny\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"danny\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"danny\",\"receiver\":\"jake\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"jake\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"alter\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"alter\",\"receiver\":\"jake\",\"timestamp\":0.0}],\"line\":[\"alter\",\"coolidge\",\"danny\",\"dayu\",\"jake\",\"kelsen\",\"wiseman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":9,\"theirs\":6},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"wiseman\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"craig\",\"danny\",\"dayu\",\"peter\",\"sam love\",\"turtle\",\"wiseman\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":9,\"theirs\":7},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"jordan\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"jordan\",\"receiver\":\"pat\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"pat\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Throwaway\",\"passer\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"D\",\"defender\":\"Anonymous\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"dan park\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"brian\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"brian\",\"receiver\":\"simmons\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"simmons\",\"receiver\":\"colin\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Catch\",\"passer\":\"colin\",\"receiver\":\"dan park\",\"timestamp\":0.0},{\"type\":\"Offense\",\"action\":\"Goal\",\"passer\":\"dan park\",\"receiver\":\"brian\",\"timestamp\":0.0}],\"line\":[\"brian\",\"colin\",\"dan park\",\"jordan\",\"pat\",\"simmons\",\"rainy\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":10,\"theirs\":7},\"lineType\":\"O\",\"finished\":true,\"elapsedTime\":0}},{\"events\":[{\"type\":\"Defense\",\"action\":\"Pull\",\"defender\":\"dayu\",\"timestamp\":0.0},{\"type\":\"Defense\",\"action\":\"Goal\",\"timestamp\":0.0}],\"line\":[\"coolidge\",\"danny\",\"dayu\",\"jake\",\"shane\",\"tuna\",\"turtle\"],\"startSeconds\":0,\"endSeconds\":0,\"summary\":{\"score\":{\"ours\":10,\"theirs\":8},\"lineType\":\"D\",\"finished\":true,\"elapsedTime\":0}}]",
      "timestamp": "2012-03-17 16:00",
      "date": "Sat, 3/17",
      "time": "4:00",
      "msSinceEpoch": 1332000000000,
      "ours": 10,
      "theirs": 8,
      "lastUpdateUtc": "2014-07-05 09:02",
      "deleted": false,
      "firstPointOline": false,
      "previousVersionAvailable": false
    }